name: Build & Deploy Documentation

on:
  push:
      branches: 
        - "*"
      tags:
        - "*"
    
  pull_request:
      branches: 
        - "*"

jobs:
  build-shared:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Wait for build to finish
      - name: Wait On Build
        uses: tomchv/wait-my-workflow@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'Static Library'
          ref: ${{ github.sha }}
          intervalSeconds: 30
          timeoutSeconds: 3600

      # Download & extract artifacts
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: 'build_linux.yml'
          workflow_conclusion: success
          name: projectm-linux-shared-latest
          path: ./artifacts

      # Run docs.sh
      - name: Run docs.sh
        run: |
          chmod +x ./docs/docs.sh
          ./docs/docs.sh

      # Deploy to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs